"""create_workspace_table

Revision ID: 4f80ff980593
Revises: 
Create Date: 2026-02-10 15:14:30.686707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f80ff980593'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_workspaces',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键ID (雪花算法)'),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('owner_clerk_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.BigInteger(), nullable=False, comment='创建人ID'),
    sa.Column('updated_by', sa.BigInteger(), nullable=False, comment='更新人ID'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_clerk_id', 'name', name='uq_workspace_owner_name')
    )
    op.create_index(op.f('ix_workspace_workspaces_name'), 'workspace_workspaces', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_workspaces_name'), table_name='workspace_workspaces')
    op.drop_table('workspace_workspaces')
    # ### end Alembic commands ###
